### ISSUE TITLE
Status? 

### ISSUE THREAD

**Issue by bkchr** [balena-io-modules/libnm-rs#1]
Hey, is this still being developed?

**Comment by majorz** [comment]
@bkchr yes, I just resynced it with the latest Rust glib libraries. Currently the Cargo.toml file is not bound to specific versions of theirs, but their git master branches instead. This will change once we complete the integration with our WiFi Connect project.

**Comment by bkchr** [comment]
Ahh nice, so you still working on it :) Ty.

**Comment by majorz** [comment]
@bkchr This upcoming release took an year to complete, but in the next days the code of this project will be merged with the `network-manager` module and published on crates.io. Closing this now :D

**Comment by bkchr** [comment]
Nice! Good to hear :) Maybe I can finally retire my own network-manage fork :) Looking forward.
